SHOE_DATABASE = [
    {"brand": "Brooks", "model": "Adrenaline GTS 26", "price": 170, "tier": "Performance", "widths": ["R", "W", "EW"], "category": "Stability", "notes": "Classic stable daily trainer."},
    {"brand": "Brooks", "model": "Ghost 18", "price": 150, "tier": "Performance", "widths": ["R", "W"], "category": "Neutral", "notes": "Reliable, versatile daily runner."},
    {"brand": "Brooks", "model": "Glycerin 23 GTS", "price": 180, "tier": "Premium", "widths": ["R", "W"], "category": "Stability", "notes": "Plush, max-cushion support."},
    {"brand": "Brooks", "model": "Launch 12", "price": 120, "tier": "Entry-Level", "widths": ["R"], "category": "Neutral", "notes": "Lightweight, snappy speed."},
    {"brand": "Brooks", "model": "Cascadia Elite", "price": 180, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "Rugged stability for trails."},

    {"brand": "Nike", "model": "Pegasus 42", "price": 145, "tier": "Performance", "widths": ["R", "W"], "category": "Neutral", "notes": "Reliable do-it-all workhorse."},
    {"brand": "Nike", "model": "Vomero 18", "price": 155, "tier": "Premium", "widths": ["R", "W"], "category": "Neutral", "notes": "High-cushion premium daily trainer."},
    {"brand": "Nike", "model": "ACG Zegama 3", "price": 180, "tier": "Premium", "widths": ["R"], "category": "Trail", "notes": "Technical terrain specialist."},
    {"brand": "Nike", "model": "Vaporfly 4", "price": 270, "tier": "Premium", "widths": ["R"], "category": "Race", "notes": "Elite-level marathon speed."},
    {"brand": "Nike", "model": "Winflo 12", "price": 110, "tier": "Entry-Level", "widths": ["R"], "category": "Neutral", "notes": "Affordable, durable daily shoe."},

    {"brand": "ASICS", "model": "Gel-Kayano 33", "price": 170, "tier": "Premium", "widths": ["R", "W", "EW"], "category": "Stability", "notes": "Top-tier support for long runs."},
    {"brand": "ASICS", "model": "Gel-Nimbus 28", "price": 170, "tier": "Premium", "widths": ["R", "W"], "category": "Neutral", "notes": "Max-cushion cloud-like feel."},
    {"brand": "ASICS", "model": "Cumulus 28", "price": 145, "tier": "Performance", "widths": ["R", "W"], "category": "Neutral", "notes": "Versatile everyday cushioning."},
    {"brand": "ASICS", "model": "Fuji Lite 7", "price": 140, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "Lightweight, agile trail racer."},
    {"brand": "ASICS", "model": "Trabuco 14", "price": 145, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "Protective, stable trail shoe."},

    {"brand": "HOKA", "model": "Clifton 10", "price": 124, "tier": "Performance", "widths": ["R", "W"], "category": "Neutral", "notes": "Plush, rocker-sole daily trainer."},
    {"brand": "HOKA", "model": "Bondi 9", "price": 175, "tier": "Premium", "widths": ["R", "W"], "category": "Neutral", "notes": "Ultra-maximalist cushioning."},
    {"brand": "HOKA", "model": "Gaviota 6", "price": 180, "tier": "Premium", "widths": ["R", "W"], "category": "Stability", "notes": "Support-focused maximalist shoe."},
    {"brand": "HOKA", "model": "Speedgoat 7", "price": 165, "tier": "Performance", "widths": ["R", "W"], "category": "Trail", "notes": "Gold standard for trail grip."},
    {"brand": "HOKA", "model": "Zinal 3", "price": 150, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "Snappy, low-profile trail racer."},

    {"brand": "New Balance", "model": "Fresh Foam 1080v15", "price": 170, "tier": "Premium", "widths": ["R", "W", "EW"], "category": "Neutral", "notes": "Soft, premium foam for daily miles."},
    {"brand": "New Balance", "model": "Fresh Foam 860v15", "price": 150, "tier": "Performance", "widths": ["R", "W", "EW"], "category": "Stability", "notes": "Consistent support for daily use."},
    {"brand": "New Balance", "model": "FuelCell Rebel Trail", "price": 150, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "Nimble, high-energy trail shoe."},
    {"brand": "New Balance", "model": "FuelCell Ellipse", "price": 212, "tier": "Premium", "widths": ["R"], "category": "Race", "notes": "Propulsive, marathon-ready."},
    {"brand": "New Balance", "model": "Fresh Foam Hierro v9", "price": 160, "tier": "Performance", "widths": ["R", "W"], "category": "Trail", "notes": "Rugged comfort for long trails."},

    {"brand": "Adidas", "model": "Adizero Evo SL", "price": 150, "tier": "Performance", "widths": ["R"], "category": "Neutral", "notes": "Lightweight, highly responsive."},
    {"brand": "Adidas", "model": "Supernova Rise 3", "price": 140, "tier": "Performance", "widths": ["R", "W"], "category": "Neutral", "notes": "Balanced, reliable daily trainer."},
    {"brand": "Adidas", "model": "Terrex Agravic Speed 2", "price": 225, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "Fast, agile mountain racer."},
    {"brand": "Adidas", "model": "Hyperboost Edge", "price": 200, "tier": "Premium", "widths": ["R"], "category": "Neutral", "notes": "Max-cushion energy return."},
    {"brand": "Adidas", "model": "Runfalcon 6", "price": 65, "tier": "Entry-Level", "widths": ["R"], "category": "Neutral", "notes": "Value-focused basic runner."},

    {"brand": "Saucony", "model": "Endorphin Speed 5", "price": 175, "tier": "Premium", "widths": ["R"], "category": "Race/Tempo", "notes": "Versatile, propulsive trainer."},
    {"brand": "Saucony", "model": "Endorphin Pro 5", "price": 240, "tier": "Premium", "widths": ["R"], "category": "Race", "notes": "Carbon-plated marathon elite."},
    {"brand": "Saucony", "model": "Triumph 24", "price": 170, "tier": "Premium", "widths": ["R", "W"], "category": "Neutral", "notes": "Premium plush daily distance."},
    {"brand": "Saucony", "model": "Guide 19", "price": 150, "tier": "Performance", "widths": ["R", "W"], "category": "Stability", "notes": "Reliable daily support."},
    {"brand": "Saucony", "model": "Peregrine 16", "price": 150, "tier": "Performance", "widths": ["R", "W"], "category": "Trail", "notes": "All-terrain technical grip."},

    {"brand": "Puma", "model": "Velocity Nitro 4", "price": 140, "tier": "Performance", "widths": ["R"], "category": "Neutral", "notes": "Durable, all-purpose foam."},
    {"brand": "Puma", "model": "Deviate Nitro 4", "price": 170, "tier": "Premium", "widths": ["R"], "category": "Neutral", "notes": "Carbon-plated daily trainer."},
    {"brand": "Puma", "model": "Deviate Pure Nitro", "price": 150, "tier": "Premium", "widths": ["R"], "category": "Neutral", "notes": "Lightweight, high-energy racer."},
    {"brand": "Puma", "model": "MagMax 2", "price": 180, "tier": "Premium", "widths": ["R"], "category": "Neutral", "notes": "Massive cushion, luxury feel."},
    {"brand": "Puma", "model": "Velocity Nitro 3", "price": 135, "tier": "Performance", "widths": ["R"], "category": "Neutral", "notes": "Dependable, grippy daily shoe."},

    {"brand": "Mizuno", "model": "Wave Rider 29", "price": 120, "tier": "Performance", "widths": ["R", "W"], "category": "Neutral", "notes": "Classic, firm-responsive ride."},
    {"brand": "Mizuno", "model": "Wave Neo Vista 3", "price": 200, "tier": "Premium", "widths": ["R"], "category": "Neutral", "notes": "Innovative, eco-conscious speed."},
    {"brand": "Mizuno", "model": "Hyperwarp Pro", "price": 250, "tier": "Performance", "widths": ["R"], "category": "Neutral", "notes": "New intro for performance pace."},
    {"brand": "Mizuno", "model": "Hyperwarp Elite", "price": 275, "tier": "Premium", "widths": ["R"], "category": "Race", "notes": "High-end competitive racing."},
    {"brand": "Mizuno", "model": "Neo Zen 2", "price": 160, "tier": "Performance", "widths": ["R"], "category": "Neutral", "notes": "Versatile, smooth daily trainer."},

    {"brand": "On", "model": "CloudMonster 3", "price": 190, "tier": "Premium", "widths": ["R"], "category": "Neutral", "notes": "Unique, high-energy cushioning."},
    {"brand": "On", "model": "Cloud 6", "price": 160, "tier": "Performance", "widths": ["R"], "category": "Neutral", "notes": "Sleek, urban-ready daily shoe."},

    {"brand": "Altra", "model": "Lone Peak 9", "price": 145, "tier": "Performance", "widths": ["R", "W"], "category": "Trail", "notes": "Wide toe box, zero-drop trail."},
    {"brand": "Altra", "model": "Timp 6", "price": 165, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "Cushioned, zero-drop trail shoe."},
    {"brand": "Altra", "model": "Superior 7", "price": 130, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "Lightweight trail shoe."},
        {"brand": "Saucony", "model": "Peregrine 16", "price": 150, "tier": "Performance", "widths": ["R", "W"], "category": "Trail", "notes": "All-terrain expert with great grip."},
    {"brand": "HOKA", "model": "Speedgoat 7", "price": 165, "tier": "Premium", "widths": ["R", "W"], "category": "Trail", "notes": "The go-to for cushioned, reliable trail miles."},
    {"brand": "HOKA", "model": "Torrent 4", "price": 130, "tier": "Affordable", "widths": ["R"], "category": "Trail", "notes": "Excellent value, nimble and lightweight."},
    {"brand": "Salomon", "model": "Speedcross 6", "price": 150, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "Deep lugs, strong for soft or muddy ground."},
    {"brand": "Altra", "model": "Lone Peak 9", "price": 145, "tier": "Performance", "widths": ["R", "W"], "category": "Trail", "notes": "Zero-drop, wide toe box classic."},
    {"brand": "La Sportiva", "model": "Bushido III", "price": 160, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "Precise, high-traction for technical terrain."},
    {"brand": "Nnormal", "model": "Kjerag 02", "price": 215, "tier": "Premium", "widths": ["R"], "category": "Trail", "notes": "Ultralight and durable for mountain racing."},
    {"brand": "La Sportiva", "model": "Prodigio Pro", "price": 225, "tier": "Premium", "widths": ["R"], "category": "Trail", "notes": "Race-ready, agile, and protective."},
    {"brand": "Brooks", "model": "Cascadia 19", "price": 150, "tier": "Performance", "widths": ["R", "W"], "category": "Trail", "notes": "Stable, long-standing all-around trail shoe."},
    {"brand": "The North Face", "model": "Altamesa 500 V2", "price": 170, "tier": "Premium", "widths": ["R"], "category": "Trail", "notes": "Great for daily high-mileage trail training."},
    {"brand": "Mount to Coast", "model": "H1", "price": 160, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "Strong road-to-trail hybrid."},
    {"brand": "On", "model": "Cloudultra Pro", "price": 260, "tier": "Premium", "widths": ["R"], "category": "Trail", "notes": "Snappy and fast for long trail efforts."},
    {"brand": "Norda", "model": "001A", "price": 285, "tier": "Premium", "widths": ["R"], "category": "Trail", "notes": "Ultra-durable with high-tech materials."},
    {"brand": "Topo Athletic", "model": "Ultraventure 4", "price": 155, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "Wide toe box with plush comfort."},
    {"brand": "Merrell", "model": "Agility Peak 6", "price": 170, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "Aggressive lugs for rocky, loose terrain."},
    {"brand": "Adidas", "model": "Terrex Agravic 4", "price": 145, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "Dependable, protective, and grippy."},
    {"brand": "ASICS", "model": "Metafuji Trail", "price": 250, "tier": "Premium", "widths": ["R"], "category": "Trail", "notes": "Maximalist foam with strong shock absorption."},
    {"brand": "HOKA", "model": "Tecton X 3", "price": 275, "tier": "Premium", "widths": ["R"], "category": "Trail", "notes": "High-energy return and very fast."},
    {"brand": "Nike", "model": "Ultrafly", "price": 160, "tier": "Premium", "widths": ["R"], "category": "Trail", "notes": "Carbon-plated trail racing shoe."},
    {"brand": "Altra", "model": "Experience Wild 3+", "price": 165, "tier": "Performance", "widths": ["R"], "category": "Trail", "notes": "High-performance non-zero-drop option."},
]